//! Connect a bot to a local (offline-mode) server and report events until it
//! spawns. Run with: `cargo run --example spawn -- [host] [port] [username]`.

use rustcraft::bot::{Bot, BotEvent};
use rustcraft::protocol::ClientOptions;
use rustcraft::registry::create_registry;

#[tokio::main]
async fn main() -> std::io::Result<()> {
    let mut args = std::env::args().skip(1);
    let host = args.next().unwrap_or_else(|| "localhost".into());
    let port: u16 = args.next().and_then(|p| p.parse().ok()).unwrap_or(25565);
    let username = args.next().unwrap_or_else(|| "RustBot".into());

    // Load the registry generated by `cargo run --bin datagen` (block/item names).
    let registry = create_registry("data", "26.1.2").ok();
    println!(
        "registry: {}",
        if registry.is_some() {
            "loaded"
        } else {
            "not found (run `cargo run --bin datagen`)"
        }
    );

    println!("Connecting to {host}:{port} as {username}…");
    let options = ClientOptions {
        host: host.clone(),
        port,
        username: username.clone(),
        access_token: None,
        uuid: None,
    };

    let mut bot = Bot::connect(options, registry).await?;
    println!("Reached PLAY state. Waiting for spawn…");

    loop {
        match bot.next_event().await? {
            Some(BotEvent::Login) => println!(
                "login: entityId={} dimension={} maxPlayers={}",
                bot.entity_id, bot.game.dimension, bot.game.max_players
            ),
            Some(BotEvent::Position) => {
                println!(
                    "position: {:?} (yaw={:.1} pitch={:.1})",
                    bot.position, bot.yaw, bot.pitch
                )
            }
            Some(BotEvent::Spawn) => {
                println!(
                    "SPAWNED at {:?} — health={} food={}",
                    bot.position, bot.health, bot.food
                );
                bot.run_command("say hello from rustcraft").await?;
                // Exercise a few actions to confirm they serialize/send live.
                bot.look(90.0, 0.0).await?;
                bot.set_held_slot(2).await?;
                bot.swing_arm().await?;
                println!("sent look + set_held_slot(2) + swing OK");
            }
            Some(BotEvent::ChunkLoad(cx, cz)) => {
                println!("chunk loaded: {cx},{cz}");
                // When the player's own chunk loads, name the blocks beneath the feet.
                let (px, py, pz) = (
                    bot.position.x as i32,
                    bot.position.y as i32,
                    bot.position.z as i32,
                );
                if cx == px >> 4 && cz == pz >> 4 {
                    for dy in 1..=4 {
                        let y = py - dy;
                        if let Some(info) = bot.block_at(px, y, pz) {
                            println!("  block at ({px},{y},{pz}) = {}", info.name);
                        }
                    }
                }
            }
            Some(BotEvent::Health) => println!("health={} food={}", bot.health, bot.food),
            Some(BotEvent::Death) => println!("died — respawning"),
            Some(BotEvent::Kicked(reason)) => {
                println!("kicked: {reason}");
                break;
            }
            Some(_) => {}
            None => {
                println!("disconnected");
                break;
            }
        }
    }
    Ok(())
}
